'use strict';
const assert = require('node:assert/strict');
const { tooltipRows } = require('../integrations/sidebar/tooltip.cjs');
const now = 1700000000000;
const rings = [{ label: 'Week', percent: 68, resetsAt: now / 1000 + 86400, tone: 'normal' }];
const credits = { count: 3, expiresAt: now / 1000 + 7200, expired: false };
const feed = { status: 'ok', latestAt: now / 1000 - 86400, forecast: 'around DevDay (Pacific Time)', watchUntil: now / 1000 + 3600 };
const rows = tooltipRows(rings, credits, feed, now);
assert.equal(rows.filter(r => r.label === 'Resets in').length, 1);
assert.equal(rows[0].value, '68% left');
assert.equal(rows[0].tone, 'normal');
assert.equal(rows.find(r => r.label === 'Forecast').value, 'Unconfirmed');
assert.equal(rows.find(r => r.label === 'Forecast').note, feed.forecast);
assert.equal(rows.find(r => r.label === 'Watch ends').tone, 'muted');
assert.ok(!tooltipRows(rings, credits, feed, now + 3600001).some(r => r.label === 'Forecast'));
assert.ok(!tooltipRows(rings, credits, {...feed, status: 'unavailable'}, now).some(r => r.label === 'Forecast'));
assert.equal(tooltipRows([], {count:null}, null, now)[0].value, 'Unknown');
assert.equal(tooltipRows([], {count:0}, null, now).length, 1);
assert.equal(tooltipRows([], {...credits, expired:true}, null, now)[0].value, 'Refresh needed');
console.log('Compact tooltip: distinct reset meanings, forecast expiry and unknown states passed');
